### ISSUE TITLE
pumi_node_getField() issue

### ISSUE THREAD

**Issue by RuixiongHu** [SCOREC/fep#10]
Hello,

I'm doing my FEP project and had some little error with the function `pumi_node_getField()`;

So far I've created a field by pumi_node_setField() successfully and can check it by postprocessing. However, when trying to accessing and extracting the value of the field at some locations using pumi_node_getField(), I'm getting error signal 11, which should be a seg fault.

I've checked the examples at the end of the documentation but found no clue. Could you plz help me with this? Here's how I did it:

```
      double *value1;
      double *value2;
      pumi_node_getField( DEPTH, nodes[0], 0, value1);
      pumi_node_getField( DEPTH, nodes[1], 0, value2);
```
DEPTH is the field handle, and this is a single DOF on node base. I've noticed while compiling it warns me of `value1, value2 might be used before set`. I don't see why this happens since for my understanding I initialized those right before using it, and this getField function should feed value to it, instead of accessing the value it's pointing to.

Thanks a lot!

**Comment by cwsmith** [comment]
Try the following.  The underlying apf call [`getNodeComponents(...)` expects the output array to already be allocated](https://github.com/SCOREC/core/blob/4446cdaeafa2f86b11444e8d256ac4d91bb25d18/apf/apfFieldData.cc#L184-L199).

```
      double value1;
      double value2;
      pumi_node_getField( DEPTH, nodes[0], 0, &value1);
      pumi_node_getField( DEPTH, nodes[1], 0, &value2);
```

**Comment by RuixiongHu** [comment]
Hi, thanks for the answer and this works!

I'll really appreciate your answer.
Thanks! 

edit: I moved the integration point questions here: https://github.com/SCOREC/fep/issues/11
