### ISSUE TITLE
ordered print out of results using std::cout << 

### ISSUE THREAD

**Issue by startrekman** [SCOREC/fep#12]
## Summary

I am unsure how to perform tasks sequentially. For example,  if when I want to print out vertex id's and regions, not only are the results jumbled up, but there are duplicates. I am using std::cout << etc.  I have thought about trying a queue or a set, but I don't see how that would improve the output. Is there any way to limit the stream output to one core/ process for assignment 2?

**Comment by cwsmith** [comment]
Hello,

You can try something like this to have each process print all its info before the next process prints:

```
for(int i = 0; i < pumi_size(); i++) {
  if( i == pumi_rank() ) {
    // print stuff
  }
  pumi_sync();
}
```

Also note that printing to `cout` or using `printf` writes to `stdout` which is buffered.  If you want unbuffered prints use `cerr` or `fprintf(stderr,...)`.

There will appear to be duplicate mesh entities if local ids are printed *without* process id info.

**Comment by cwsmith** [comment]
I'm closing this ticket.  Please reopen it if this is still an issue.
