### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by goinea** [SCOREC/fep#13]
![Hw 1 error](https://user-images.githubusercontent.com/78876542/110416248-5ae3e580-8061-11eb-8d78-7afb8f0bec0a.PNG)
What could have caused this?

**Comment by cwsmith** [comment]
It is most likely an invalid access to one of the vertices fed into `buildElement(...)`.

**Comment by cwsmith** [comment]
I'm closing this ticket.  Please reopen it if this specific problem is still an issue.
