### ISSUE TITLE
Vi error E514 write error (file system full?)

### ISSUE THREAD

**Issue by startrekman** [SCOREC/fep#14]
I am getting a vi write error and I am not sure how to fix it. I started by doing rm *slurm* to get rid of those files to see if it was some long output file. It was not. When I look at the df command, I am seeing that there is 110% of memory use and am not sure how to fix it
![image](https://user-images.githubusercontent.com/80167275/111055947-08cc0700-8449-11eb-9277-c77ac1ebc0bb.png)

**Comment by cwsmith** [comment]
Hello,

`df` is reporting the usage for different portions of the filesystem.  Your suspicion was correct; the **shared** home directory for the FEP5 project is full (`df -h ~` will report this).  I've emailed the large consumers and asked them to move their files elsewhere.  Thank you.

**Comment by cwsmith** [comment]
Space in the FEP5 home directory has been freed.  Please reopen this ticket if the problem persists.  

Thanks again for reporting the problem.

**Comment by startrekman** [comment]
Duplicate of #

I am not sure but the memory seems to be full again, but I am not sure if that would cause the programs not to run. I am able to save it in vi. 
![image](https://user-images.githubusercontent.com/80167275/111241554-c551d400-85d3-11eb-978e-9d0660dc0a6a.png)

**Comment by cwsmith** [comment]
@startrekman 

Disk usage in the home directory is fine:

```
FEP5smth@dcsfen02: ~ $ df -h ~
Filesystem      Size  Used Avail Use% Mounted on
gpfs.v           10G  1.2G  8.9G  12% /gpfs/u
```

The machine is likely just busy.  See the status page and/or the output of `sinfo` for information on the system usage:

https://secure.cci.rpi.edu/wiki/status/
