### ISSUE TITLE
Storing different pMeshEnt variables in the same dynamic array.

### ISSUE THREAD

**Issue by dhyan1272** [SCOREC/fep#17]
is it possible to store the 'pMeshEnt' type variables vertex and edges in the same data structure as std::vector or std::deque?
Both are of the same data type "pMeshEnt" but I am getting segmentation fault while trying to store both in the same dynamic array.

**Comment by cwsmith** [comment]
Yes, they can both be stored in the same dynamic array.  If you have a small example code that segfaults I can take a look.

**Comment by dhyan1272** [comment]
std::deque<pMeshEnt> q;
                   std::vector<pMeshEnt> edges;
                   std::vector<pMeshEnt> list;
                   pumi_ment_getAdj(vtx,1, edges);
                   .
                   .
                   .

                   bool check_node=hasNode(mesh, edges[i]);
                   if(check_node){
131
132                         int edge_node       = pumi_node_getNumber(numbers_edge, edges[i], 0, 0);
133                         int other_vertex_id = pumi_node_getNumber(numbers, other_vertex, 0, 0);
134
135                         int x1=std::count(q.begin(),q.end(),other_vertex);      //Check if other_vertex in queue
136
137                         if(     ((x1>0) || (set_label[other_vertex_id]==1)) && (set_label[edge_node]==0)        ){
138
139                                 label_node=label_node-1;
140
142
143                         else{
144                                 q.push_back(edges[i]);  //Segm faults whenever I try to push an edge entity, NO     issue in pushing vertices (for mesh 1 and 2)

145                                 printf("Top %d\n",pumi_ment_getTopo(edges[i]));
146                                 list.push_back(other_vertex);
147
148                         }
149
150
151                 }


________________________________

**Comment by cwsmith** [comment]
This discussion continued offline.
