### ISSUE TITLE
How to get midpoint and mid-face nodes?

### ISSUE THREAD

**Issue by startrekman** [SCOREC/fep#18]
Basically, I think I want to be able to call n = field -> countNodesOn(e) and iterate over each node on the edge to get every node on a pMeshEnt. I want this so that I can get the mid-face nodes as well as mid-edge nodes. I am assuming the field is not a pField. However, I am having trouble figuring out the correct field to create/ how to create it. From there, I am not sure how to identify each node. Thank you for your help.

**Comment by cwsmith** [comment]
You are using the `apf` interface now?  I'd suggest sticking with the pumi api as it has documentation.

I thought the question of edge nodes and face nodes and usage with a numbering was discussed here: https://github.com/SCOREC/fep/issues/16

If you use the pumi apis, then search for `node` functions in the pumi users guide.  I think you'll find the info you need about node coordinates.

**Comment by startrekman** [comment]
In 16, I was wondering why the ID did not change. It seems it does not, but there is a new numbering scheme that shows up in paraview that shows the new numbering for the nodes and faces lableld. 

So, I seem to be able to find each node at the vertex of the mesh and label the faces. However, there are nodes in between the two vertexes and I am not sure how to get those so that they can be labeled. For an order 2 triangle element in 2D, there seem to be 3 vertexes and 3 mid-point nodes. I am only finding the vertexes and am not sure how to get the other nodes. 

I am not sure where this is going with this but it seems you are suggesting something like the following: we know the coordinates to both vertexes, and we have and we can compare the location of point. So if i knew the mesh only had one midpoint node, I could identify it by the coordinates not equaling that of the vertex. However, I still do not know how to determine the number of nodes on an edge. Secondly, even if I could get the node vertex, I do not see a way of converting that into a node. Also, I do not see a way of getting the number of nodes using 

int pumi_shape_getNumNode (
pShape /* in */ s,
int /* in */ t)

because the input is an edge or a face. 

I can probably hard code it because I know the dimensions of the mesh/ etc. but I don't think that is the point and it sounds like there is a way to get all the nodes on an edge that has an arbitrary number of nodes. Thank you for your help.

**Comment by startrekman** [comment]
![image](https://user-images.githubusercontent.com/80167275/111342303-b65d3700-8650-11eb-8c73-3247d5eb0ae5.png)

**Comment by startrekman** [comment]
![image](https://user-images.githubusercontent.com/80167275/111342450-dab91380-8650-11eb-9fb7-7864b197660c.png)

**Comment by cwsmith** [comment]
> So, I seem to be able to find each node at the vertex of the mesh and label the faces. However, there are nodes in between the two vertexes and I am not sure how to get those so that they can be labeled. For an order 2 triangle element in 2D, there seem to be 3 vertexes and 3 mid-point nodes. I am only finding the vertexes and am not sure how to get the other nodes.

You can use the set/get functions on the mesh edges.

> I am not sure where this is going with this but it seems you are suggesting something like the following: we know the coordinates to both vertexes, and we have and we can compare the location of point. So if i knew the mesh only had one midpoint node, I could identify it by the coordinates not equaling that of the vertex. However, I still do not know how to determine the number of nodes on an edge. Secondly, even if I could get the node vertex, I do not see a way of converting that into a node. Also, I do not see a way of getting the number of nodes using

No. I assumed 'midpoint' meant you wanted the coordinates of the point at the middle of an edge in cartesian space....

Please email me.  We should probably just have a brief webex to clear up the confusion.

**Comment by startrekman** [comment]
Works for me, thank you for your help and time. Can you send me a webex 
link for whatever time works for you?

Very Respectfully,
AJ

**Comment by cwsmith** [comment]
Discussion continued offline.  Please reopen if needed.

A key point that was not clear: a `pMeshEnt` is a pointer to a mesh vertex, edge, face, or region.  The user guide has been updated to be more explicit about this: https://scorec.rpi.edu/pumi/PUMI.pdf (page 31 of 90).
