### ISSUE TITLE
"not declared, queue.pop()" issues

### ISSUE THREAD

**Issue by goinea** [SCOREC/fep#19]
## Summary
"void value not ignored as it aught to be", not sure how to ignore when I need to in the code below. Also, per some of the examples in the psudo code and online that I've seen, if then statements can be used but even with similar syntax do not work here.
## Code 
         while (queue1.size(e) > 0) { // process entities until the queue is empty, change to text to 
                                                          queue1.size() > 0 to adjust the needed language
                  e = queue1.pop(); //changed entity to "e", and changed e=q dequeue to queue1.pop to remove 
             something from the queue
                 node = pumi_numbering_getNumNode(pNumbering(mesh));  //changed entity to "e", also 
                          changed e 
                getNode() to node=pumi_numbering_getNumNode(pNumbering(mesh));
                 if (pumi_ment_isOwned(node)) //adding pumi_ment_isOwned(node), to specify tagging the 
                           owned entity
                 then {
                 labelnode = labelnode -1;
                 node setLabel(labelnode);
         }

Error message:
 44 |    e = queue1.pop()//changed entity to "e", and changed e=q dequeue to queue1.pop to remove something from the queue
      |        ~~~~~~~~~~^~
/gpfs/u/home/FEP5/FEP5gnsd/a2/a2.cc:46:25: error: 'node' was not declared in this scope
   46 |   if (pumi_ment_isOwned(node)) //adding pumi_ment_isOwned(node), to specify tagging the owned entity
      |                         ^~~~
/gpfs/u/home/FEP5/FEP5gnsd/a2/a2.cc:47:2: error: 'then' was not declared in this scope
   47 |  then {

**Comment by cwsmith** [comment]
Please fix the formatting (i.e., indentation) of the code snippet posted.  

There are missing semicolons on multiple lines.

**Comment by cwsmith** [comment]
That looks better.  Are the compile errors fixed?

The long comments at the end of each line also are not helping readability.  I'd suggest moving all but the shortest comments (i.e., one to three words) to the line above *and* breaking all lines over that extend beyond the 80th column.  For example, this:

```
                  e = queue1.pop(); //changed entity to "e", and changed e=q dequeue to queue1.pop to remove 
             something from the queue
```

becomes

```
                  //changed entity to "e", and changed e=q dequeue
                  // to queue1.pop to remove something from the queue
                  e = queue1.pop(); 
```

**Comment by goinea** [comment]
Sounds good, will do. I still have some compile errors with parentheses but the real issue is using the adjacent information in the logic of the pseudo code without using the same while loops in the other examples instead using the if, for, and do loops. Making slow but steady progress, hopefully compiles and converges to readable files soon. Also, assuming you haven’t always had a Mac, did you have to download a package to send files from Linux to windows?
Best,
Adam

**Comment by cwsmith** [comment]
> Also, assuming you haven’t always had a Mac, did you have to download a package to send files from Linux to windows?

WSL in windows10 has support for `scp`.

winscp is a graphical tool I've used before: https://winscp.net/eng/index.php

VSCode also supports file transfers.
