### ISSUE TITLE
a4: copying a4 directory

### ISSUE THREAD

**Issue by anilkamat** [SCOREC/fep#20]
## Summary
@mortezah I am trying to copy a4 directory to my home directory but it is giving me some error saying "The directory doesn't exist ". I followed the same copying command as in the previous assignments. 
## Details
command used: cp –r ~/barn-shared/fep/a4 ~/.
Error: 
cp: cannot stat '\342\200\223r': No such file or directory
cp: omitting directory '/gpfs/u/home/FEP5/FEP5kmtn/barn-shared/fep/a4'

**Comment by mortezah** [comment]
@anilkamat  I can copy things without any problems on my end. In the command that you copied in the issue `cp –r ~/barn-shared/fep/a4 ~/.` it seems that you are using a character that is not a "dash" before the dash-r option. Can you copy and paste this one and see if the cp is successful `cp -r ~/barn-shared/fep/a4 ~/.`

**Comment by anilkamat** [comment]
@mortezah Yes, you are right. The character "-" was the unknown one. 
It worked, Thank you.
