### ISSUE TITLE
a4: output file doesn't exit

### ISSUE THREAD

**Issue by anilkamat** [SCOREC/fep#21]
## Summary
@mortezah  I am able to compile the program using "make" after setting up all the shape functions. However, when I try to see the output file (slurm-), it terminates with exit code 2. I looked at the error on the internet and found that it may happen when the file doesn't exist. I also downloaded the a4 directory to my local computer to see in ParaView but didn't find any ".vtk" file there. I think the executable file is not being generated. Can you help me with this? 
I have posted below the commands that I used. Hope that's readable. 
## Code 
**[FEP5kmtn@erp14 a4]**$ vi LagrangeElements.hpp
**[FEP5kmtn@erp14 a4]**$ sbatch ./run.sh ./a4_projection --mesh ./data/1x1_square_quad.mesh --order 1
Submitted batch job 16810
**[FEP5kmtn@erp14 a4]**$ ls
LagrangeElements.hpp  a4_advection_diffusion.cpp  a4_element_stiffness.cpp  data              slurm-16776.out  slurm-16779.out  slurm-16808.out
Makefile              a4_convergence_rate.cpp     a4_interpolation.cpp      erp_env_setup.sh  slurm-16777.out  slurm-16806.out  slurm-16810.out
README.md             a4_diffusion.cpp            a4_projection.cpp         run.sh            slurm-16778.out  slurm-16807.out
**[FEP5kmtn@erp14 a4]**$ cat slurm-16810.out
srun: error: erp07: task 0: Exited with exit code 2
slurmstepd: error: execve(): /gpfs/u/home/FEP5/FEP5kmtn/a4/./a4_projection: No such file or directory
**[FEP5kmtn@erp14 a4]**$

**Comment by mortezah** [comment]
@anilkamat the result of `ls` suggests that there is no executable. Did you follow the steps 1-3 mentioned in the README here https://github.com/SCOREC/fep/blob/master/a4/README.md

**Comment by anilkamat** [comment]
Yes, I followed the exact same steps.

**Comment by mortezah** [comment]
@anilkamat I am just wondering if after calling `make` you also happened to call `make clean`. If yes, that could explain why there are no execrable in your directory.

Also when you call `make` what do you see on your terminal?

**Comment by anilkamat** [comment]
Yes, you are right. I was using make clean after make and it was removing all the executables. Now I am can see the executables and can also see the output in paraveiw. Thank you very much. @mortezah
