### ISSUE TITLE
Passwordless ssh

### ISSUE THREAD

**Issue by goinea** [SCOREC/fep#24]
## Summary
- Passwordless ssh is not working and I reinstalled it using the instructions here: https://secure.cci.rpi.edu/wiki/landingpads/Passwordless_SSH/

## Details
- Still the password option does not work and when trying to run ./setup.sh , ./build.sh I get a "command not found error." Is there a way to work around this that you have done before or should I just contact cci?
## Code 
N/a

**Comment by cwsmith** [comment]
@goinea Thanks for the heads up.  There was a power outage at the CCI yesterday.  

I was unable to connect from `blp01` to `erpfen01`

```
$ ssh erpfen01
ssh: connect to host erpfen01 port 22: No route to host
```

My guess is that the ERP cluster has not be fully restored.  I emailed support, and Cc'd you.  When there is an update I'll post the info to this issue.  The problem may not be resolved until Monday.

**Comment by goinea** [comment]
Cameron,
Thank you for the heads up, I’ll make the adjustments.
Best,
Adam

**Comment by cwsmith** [comment]
@goinea @joshia5 `erpfen01` is now accessible, but `erp14` is still prompting for a password.  From what I can tell, the home directories are not being mounted, which will likely cause a variety of problems that will prevent execution of the setup, build, and run scripts.  I'll post additional updates as they become available.

**Comment by goinea** [comment]
Thank you Cameron.

**Comment by cwsmith** [comment]
@goinea @joshia5 ssh to `erp14` is working now.

**Comment by goinea** [comment]
Thanks

**Comment by joshia5** [comment]
@cwsmith thanks for getting this up over the weekend!

**Comment by cwsmith** [comment]
@goinea @joshia5 You're welcome.
