### ISSUE TITLE
Quadrature points ordering in MFEM

### ISSUE THREAD

**Issue by dhyan1272** [SCOREC/fep#25]
## Summary
Does the quadrature points follow similar ordering as the nodes in MFEM?
## Details
While looping over the quadrature points for a quadrilateral element, the quadrature points are
j=0 ( 0.211325,0.211325)
j=1 (0.788675, 0.211325)
j=2 (0.211325 0.788675)
j=3 (0.788675 0.788675)
whereas node numbering is
node0 (0,0)
node1 (1,0)
node2 (1,1)
node3 (0,1)

**Comment by mortezah** [comment]
@dhyan1272 there is no need for them to be in the same order.
