### ISSUE TITLE
a4

### ISSUE THREAD

**Issue by aj-page** [SCOREC/fep#26]
srun: error :erp07: task 0: Exited with exit code 13
slurmstepd: error: execve(): a4_element_stiffness.cpp: Permission denied 

Very slightly modified (if not totally unmodified) a4_stiffness.cpp is causing this error. What could the error be?

**Comment by cwsmith** [comment]
@aj-page 

There is no `srun` command that we provided in a script (that I'm aware of) that should be doing anything with the source `.cpp` file. I suspect the source or build  directory is corrupted somehow.

Please provide the following info:
- the command you executed
- the directory the command was run from
- the name of the machine you were logged into (i.e., `erp14`)

Copying and pasting this info directly from the terminal you are using would be ideal.  For example:

```
FEP5smth@erp14: ~ $ cp -r ~/barn-shared/fep/a4 .
FEP5smth@erp14: ~ $ cd a4
FEP5smth@erp14: ~/a4 $ source erp_env_setup.sh
FEP5smth@erp14: ~/a4 $ make 
... omitted make output ...
FEP5smth@erp14: ~/a4 $ sbatch ./run.sh ./a4_projection --mesh ./data/1x1_square_quad.mesh --order 1
Submitted batch job 17628
FEP5smth@erp14: ~/a4 $ cat slurm-17628.out
Options used:
   --mesh ./data/1x1_square_quad.mesh
   --vrefine 1
   --mrefine 0
   --order 1
```

**Comment by aj-page** [comment]
I still don't know what happened, but I just started over with a clean file and it is now working.
