### ISSUE TITLE
pumi_node_getNumber usage

### ISSUE THREAD

**Issue by tuckerbabcock** [SCOREC/fep#3]
Hi,

I'm trying to get the numbers of elements and vertices by `int elem_id = pumi_node_getNumber(elem_numbers, tempElem, 0, 0);`  or `int vertex_id = pumi_node_getNumber(vtx_numbers, vertices[i], 0, 0);`, and after creating them with `pNumbering elem_numbers = pumi_numbering_createOwnDim(mesh, "elem_numbers", pumi_mesh_getDim(mesh));` and `pNumbering vtx_numbers = pumi_numbering_createOwnDim(mesh, "vtx_numbers", 0);`. In these both `tempElem` and `vertices[i]` are of type `pMeshEnt`. 

After building with `./build.sh a1quad `, and running with `sbatch ./run.sh ./build/a1quad`, the slurm outfile reads: `isNumbered(n,e,node,component) failed at /gpfs/u/barn/CCNI/CCNIsmth/systemSoftware/core/apf/apfNumbering.cc + 157 
2019-02-09 19:01:36.521 (WARN ) [0xfffa2899160] 2335514:ibm.runjob.client.Job: terminated by signal 6
2019-02-09 19:01:36.522 (WARN ) [0xfffa2899160] 2335514:ibm.runjob.client.Job: abnormal termination by signal 6 from rank 0`

I don't understand this error and based on pages 65 and 67 of the PUMI User's Guide I believe I'm calling these functions correctly. Any help would be appreciated.

**Comment by cwsmith** [comment]
Was `pumi_mesh_freeze(mesh)` called before the numbering was created and accessed?

On the BGQ you can check the meaning of signals by running the command `man 7 signal`.

**Comment by tuckerbabcock** [comment]
I did not call `pumi_mesh_freeze(mesh)` before. This solved my problem. Thank you!
