### ISSUE TITLE
Can't run code, "block is unavailable due to a previous failure"

### ISSUE THREAD

**Issue by garobed1** [SCOREC/fep#4]
![output](https://user-images.githubusercontent.com/43361579/52980228-254eff80-33a7-11e9-9ab2-e5e16a73e844.PNG)

I've been getting this error today trying to run my code for assignment 1.  The output files for any run look like this image. Is this something I can fix?

**Comment by cwsmith** [comment]
I was able to reproduce the error.  I'll submit a support ticket.

```
FEP4smth@q2: ~/fep/a1 (master)$ cat slurm-930246.out
2019-02-18 18:44:59.585 (FATAL) [0xfff9e6d9160] 571:ibm.runjob.client.Job: could not start job: block is unavailable due to a previous failure
2019-02-18 18:44:59.586 (FATAL) [0xfff9e6d9160] 571:ibm.runjob.client.Job: node R21-M0-N10-J08 is not available: Software Failure
FEP4smth@q2: ~/fep/a1 (master)$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE MIDPLANELIST
debug        up    1:00:00    128    err bgq0210
debug        up    1:00:00   1792  alloc bgq[0110x0211]
debug        up    1:00:00    128   idle bgq[0210x0211]
```

**Comment by wangz23** [comment]
I have the same issue. My codes were executable and were able to show outputs.

**Comment by cwsmith** [comment]
A ticket was submitted last night.  We should hear back sometime today about this.

**Comment by cwsmith** [comment]
The CCI has fixed the problem.
