### ISSUE TITLE
LG Segment Range

### ISSUE THREAD

**Issue by BryanMcKeever** [SCOREC/fep#40]
It is given in _LG_QuadrilateralElement::CalcShape_ that in MFEM quads are defined on [0,1]x[0,1]. Can we assume then that the LG segments will be defined on [0,1] vs the transition isoparametric [-1,1]?

**Comment by cwsmith** [comment]
Yes.  The shape functions being implemented are using Gauss-Lobato quadrature:

https://github.com/SCOREC/fep/blob/77d8fc0493dac21f26d89b68870f3de9bd96ee4a/a4/LagrangeElements.hpp#L33
(and elsewhere, search for `BasisType::GaussLobatto`)

which uses the [0,1] range as described here:

https://github.com/mfem/mfem/blob/c8801d0d27fc060c1f8d42a346e9b5cfef5a2575/fem/intrules.cpp#L469-L470.

Thanks to @mortezah for the help.

**Comment by BryanMcKeever** [comment]
Thank you, @cwsmith and @mortezah!
