### ISSUE TITLE
Element Span for Stiffness Matrix

### ISSUE THREAD

**Issue by BryanMcKeever** [SCOREC/fep#42]
Just to confirm/clarify: for Task 1, Part 4, the element stiffness matrix for the diffusive term is just for one element in the mesh, meaning the domain in physical coordinates is not [0,1]x[0,1] but rather a subset of that? Thanks.

**Comment by cwsmith** [comment]
That sounds correct; the domain of the element that we are computing the stiffness matrix for is a subset of the domain of the entire mesh.
