### ISSUE TITLE
Negative # of edges while loading parallel mesh

### ISSUE THREAD

**Issue by geyan3566** [SCOREC/fep#5]
Hi,

In assignment 2 (dir a3 in barn-shared), the summary given by loading of the parallelMesh.smb has negative number of edges.

  2 === mesh size and tag info ===
  3 # global ent: v 71, e -967505719, f 134, r 59322971

Thanks,
Ge

**Comment by cwsmith** [comment]
Thanks for pointing out this bug.  It is now fixed and the PUMI install on the BGQ is being updated.

**Comment by cwsmith** [comment]
The PUMI install is complete.  Please run the build script again to link against the new PUMI libs.
