### ISSUE TITLE
PCU_Comm_Pack called at the wrong time

### ISSUE THREAD

**Issue by RuixiongHu** [SCOREC/fep#6]
Hi, in assignment 3 while I was trying to send data across processes, it's compiled but in output file I received this message:

PUMI error: PCU_Comm_Pack called at the wrong time

I used PCU_Comm_Begin before any packing, and my method was mostly following the remote numbering example in the intro pdf. So I would like to know what's the possible cause for this error.

Thanks!

**Comment by cwsmith** [comment]
Looking at the [`pumi3.cpp`](https://github.com/SCOREC/pumi-intro/blob/ac38fccc154d5bfce820500d4b6456adfc5a5006/pumi3.cc) example from https://www.scorec.rpi.edu/~seol/PUMI-intro.pdf, I'm guessing that the call the [`PCU_Comm_Begin()`](https://github.com/SCOREC/pumi-intro/blob/ac38fccc154d5bfce820500d4b6456adfc5a5006/pumi3.cc#L31) is missing before the calls to `PCU_Comm_Pack()`.  

Note, every round of peer-to-peer PCU communications needs the begin, pack, send, receive, and unpack sequence of calls.

**Comment by RuixiongHu** [comment]
Thanks, this is actually the example I followed. And I've included PCU_Comm_Begin().

I would like to know if inside while(receiving) loop, after unpacking, can I directly do a pack inside the receive loop? Or do I have to exit the receive function and then do another packing? I guess this might be my error.

And I would also like to know do I have to place pumi_sync every time after receiving, since if one process finished receiving and starts to send the second round message, then the other process, if still receiving the first round message, might receive this second round continuously.

Thanks!

**Comment by cwsmith** [comment]
> I would like to know if inside while(receiving) loop, after unpacking, can I directly do a pack inside the receive loop? Or do I have to exit the receive function and then do another packing? I guess this might be my error.

This is the error, each round of peer-to-peer communications must be independent; `PCU_Comm_Pack` cannot be called until all the previous round of receives are complete and `PCU_Comm_Begin` was called again.
 
> And I would also like to know do I have to place pumi_sync every time after receiving, since if one process finished receiving and starts to send the second round message, then the other process, if still receiving the first round message, might receive this second round continuously.

Calling pumi_sync (a wrapper of `PCU_Comm_Barrier`) after a peer-to-peer round is not required.  The [receive loop](https://github.com/SCOREC/pumi-intro/blob/ac38fccc154d5bfce820500d4b6456adfc5a5006/pumi3.cc#L46) combined with `PCU_Comm_Begin` ([which contains a barrier](https://github.com/SCOREC/core/blob/2cfbd41463f4b8c81e24a973034742f36d598165/pcu/pcu_msg.c#L97)) ensures all messages have arrived before the next round starts.

**Comment by cwsmith** [comment]
I assume this is resolved now and will close this issue.
