### ISSUE TITLE
a3 - Labeling face elements through tagging

### ISSUE THREAD

**Issue by Samiullah-Malik** [SCOREC/fep#7]
Hi,
We are asked in assignment 3 to reorder and label face elements. To label face elements, I have created an integer pMeshTag handle. Then I have used setIntTag to set integer data on each face corresponding to its number. However, I am not able to locate and visualize any tagdata in Paraview. 
Is tagging the correct approach to label face elements?

**Comment by cwsmith** [comment]
To visualize data associated with mesh entities a `Field` or `Numbering` must be created.

Re: @RuixiongHu
> Can I also ask how to label a mesh face? Seems pumi_numbering_create() tend to create label onto nodes but not other dimensions, while pumi_numbering_createOwnDim() does not allow customized numbering order.

I suggest creating two numbering objects, one for the `nodes` and one for the `elements`.

@seegyoung Can the  numbering returned by `pNumbering pumi_numbering_createOwn(...)` be modified with `void pumi_node_setNumber(...)`?  Page 65 of the [user's guide](https://www.scorec.rpi.edu/~seol/PUMI.pdf) doesn't indicate that the field is 'read only'.

If there is a 'read only' restriction, you can alternatively create an element field with `pumi_numbering_create(...)` using a `shape` from `pumi_shape_getConstant(...)`, and a nodal field using `pumi_numbering_create(...)` with a `shape` from the shape set on the mesh (linear or quadratic).
