### ISSUE TITLE
a3 - check if face/edge has node 

### ISSUE THREAD

**Issue by RuixiongHu** [SCOREC/fep#8]
Hi,

Can I ask in assignment 3, what is the function used when I wanna determine if a face or a edge has node on it?

I saw pumi_shape_hasNode but it takes a pShape and general topology as input, but not a specific mesh entity

Thanks

**Comment by cwsmith** [comment]
PUMI only supports meshes with homogenous curvature; i.e., the approximation order (linear, quadratic, etc.) of a given mesh entity is the same for all entities of the same dimension.  Given that, I think you'll want to call `pShape pumi_mesh_getShape (pMesh /* in */ m)` and then use a combination of `int pumi_shape_getNumNode(...)` and `int pumi_shape_hasNode(...)`.  

Note, each `Field` on the mesh can can have a different distribution of nodes on the mesh entities.

@seegyoung @mortezah - please comment if I have not explained this correctly/clearly.

**Comment by RuixiongHu** [comment]
Thanks for the help. 

Can I also ask how to label a mesh face? Seems pumi_numbering_create() tend to create label onto nodes but not other dimensions, while pumi_numbering_createOwnDim() does not allow customized numbering order.

This question is the same as the one asked in the other open issue.

Thanks

**Comment by cwsmith** [comment]
You're welcome.  I'll reply the face labelling question in the other issue: #7 .

**Comment by cwsmith** [comment]
I'm guessing this is resolved.  Please reopen as needed.
